[build]
  base = "."
  command = "echo \"no build\""
  publish = "frontend"
  functions = "forum-app/netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
