[build]
  command = "cd forum-app/netlify/functions && npm install"
  publish = "forum-app/frontend"
  functions = "forum-app/netlify/functions"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
